### ISSUE TITLE
購入完了画面作成

### ISSUE THREAD

**Issue by shunsuke-tamura** [scla-sagauniv/tumaguro#24]
見た目だけ

**Comment by yuuki1005** [comment]
#デザイン案


![Image](https://github.com/scla-sagauniv/tumaguro/assets/132263662/01fa3f2a-d539-4c02-8f9c-b1240bfac1ad)

**Comment by yuuki1005** [comment]
#完成
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>購入完了画面</title>
        <link rel="stylesheet" type="text/css" href="style.css"/>
    </head>
    <body>
        <p class="purchase margin-top">ありがとうございます。注文が確定されました。</p>
        <p class="purchase">商品を次のお届け先へ発送します。</p>
      <div class="Address">
        <p class="address-ditail">〒840-8502佐賀市本庄町1</p>
        <p class="address-ditail">Hogehoge Jp G.K</p>
      </div>
      <button class="button-continue" type="submit">ショッピングを続ける</button>
    </body> 
</html>   
```

```css
.header-title{
    text-align: center;
}
.search-form{
    display: flex;
    margin: 20px o;;
    justify-content: center;
}
.search-form input[type="text"]{
    width: 500px;
    margin-right: 0px;
    border-color: black;
}
.button-header{
    background-color: rgb(250, 169, 112);
    color: black;
    border-color: black;
    padding: 5px 10px;
    cursor: pointer;
    margin-right: 50px;
}
.button-header:hover{
    background-color: rgb(255, 106, 0);
}
```
