### ISSUE TITLE
カートの中身一覧画面を作る

### ISSUE THREAD

**Issue by shunsuke-tamura** [scla-sagauniv/tumaguro#3]
一旦見た目だけ

**Comment by taira7** [comment]
```html
<!DOCTYPE html>
<html>
  <head>  
    <title>ショッピングカート</title>
    <link rel="stylesheet" type="text/css" href="style.css" />
  </head>
  <body>
    <h1>ショッピングカート</h1>
    <div class="grid-container-left">
        <div class="left-column">商品1</div>
        <div class="left-column">商品2</div> 
    </div>
    <div class="grid-container-right"> 
       <div class="paypay">
        <div class="right-sum">小計</div>
        <div class="right-money">値段</div>
        <button class="cash-register">レジに進む</button>
       </div> 
       <div class="best-goods"> 
        <div class="right-column">あなたへのおすすめ</div>
        <p>・おすすめ商品1</p>
        <p>・おすすめ商品2</p>
       </div> 
    </div>
  </body> 

```
```css

.grid-container {
    display: flex;
    /* grid-template-columns: 1fr 1fr; 2つの等しい幅の列 */
    gap: 10px; /* グリッドアイテム間の間隔 */
  }
  
  .left-column {
    grid-column: 1 / 2; /* 1列目から2列目まで */
    padding: 20px;
  }
  
  .grid-container-right {
    position: fixed;
    right: 60px;
    top: 100px;
    width: 260px;
    background-color: khaki;
 }

  .right-sum {
    grid-column: 2 / 3; /* 2列目から3列目まで */
    padding: 20px;
  }

  .right-money{
    background-color: #ffffff;
    padding: 30px;
  }

  .paypay{
    border: 3px solid;
    border-color: #c0c0c0;
  }

 .right-column{
    padding: 40px;
 }

 .cash-register{
    padding: 20px;
    width: 100%;
    background-color: yellowgreen;
 }

 .cash-register:hover{
    background-color: aqua;
 }

 .best-goods{
    border: 2px solid;
    border-color: #a9a9a9;
 }

```

**Comment by tt1125** [comment]
# 完成
```html
<!DOCTYPE html>
<html>
  <head>  
    <title>ショッピングカート</title>
    <link rel="stylesheet" type="text/css" href="style.css" />
  </head>
  <body>
    <h1>ショッピングカート</h1>
    <div class="grid-container-left">
      <div class="grid-item">

        <img class="product-image" src="static/tori.jpg" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/tori.jpg" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/tori.jpg" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/tori.jpg" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/tori.jpg" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/tori.jpg" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/tori.jpg" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/tori.jpg" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      
    </div>
    <div class="grid-container-right"> 
       <div class="paypay">
        <div class="right-sum">小計</div>
        <div class="right-money">値段</div>
        <button class="cash-register">レジに進む</button>
       </div> 
       <div class="best-goods"> 
        <div class="right-column">あなたへのオススメ</div>
        <p>・オススメ商品1</p>
        <p>・オススメ商品2</p>
       </div> 
    </div>
  </body> 
```
```CSS
.grid-container {
  display: flex;
  /* grid-template-columns: 1fr 1fr; 2つの等しい幅の列 */
  gap: 10px; /* グリッドアイテム間の間隔 */
}

.left-column {
  grid-column: 1 / 2; /* 1列目から2列目まで */
  padding: 20px;
}

.grid-container-right {
  position: fixed;
  right: 60px;
  top: 100px;
  width: 260px;
  background-color: khaki;
}

.right-sum {
  grid-column: 2 / 3; /* 2列目から3列目まで */
  padding: 20px;
}

.right-money{
  background-color: #ffffff;
  padding: 30px;
}

.paypay{
  border: 3px solid;
  border-color: #c0c0c0;
}

.right-column{
  padding: 40px;
}

.cash-register{
  padding: 20px;
  width: 100%;
  background-color: yellowgreen;
}

.cash-register:hover{
  background-color: aqua;
}

.best-goods{
  border: 2px solid;
  border-color: #a9a9a9;
}
.grid-item {gap: 50px;
  align-items: center;
  width: 70%;
  display: flex;
  border: 1px solid #ccc;
  padding: 0;
  text-align: left;
}

.grid-item p, h3 {
  margin: 0;
}

.product-image {
  max-width: 20%;
  height: auto;
}

.product-price{
  color: #B12704;
  font-size: 20px;
}
```

**Comment by taira7** [comment]
# 完成　修正版
```html
<!DOCTYPE html>
<html>
  <head>  
    <title>ショッピングカート</title>
    <link rel="stylesheet" type="text/css" href="style.css" />
  </head>
  <body>
    <h1>ショッピングカート</h1>
    <div class="grid-container-left">
      <div class="grid-item">

        <img class="product-image" src="static/test.png" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/test.png" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/test.png" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/test.png" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/test.png" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/test.png" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/test.png" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      <div class="grid-item">

        <img class="product-image" src="static/test.png" alt="商品1" />
        <h3>商品1</h3>
        <p class="product-price">¥1,000</p>
        <button type="submit">後で買う</button>
        <button type="submit">削除</button>
      </div> 
      
    </div>
    <div class="grid-container-right"> 
       <div class="paypay">
        <div class="right-sum">小計</div>
        <div class="right-money">値段</div>
       </div> 
        <button class="cash-register cash-register-margin">レジに進む</button>
       <div class="best-goods"> 
        <div class="right-column">あなたへのオススメ</div>
        <p>・オススメ商品1</p>
        <p>・オススメ商品2</p>
       </div> 
    </div>
  </body> 
</html>
```

```css
.grid-container {
    display: flex;
    /* grid-template-columns: 1fr 1fr; 2つの等しい幅の列 */
    gap: 10px; /* グリッドアイテム間の間隔 */
  }
  
  .left-column {
    grid-column: 1 / 2; /* 1列目から2列目まで */
    padding: 20px;
  }
  
  .grid-container-right {
    position: fixed;
    right: 60px;
    top: 100px;
    width: 260px;
  }
  
  .right-sum {
    grid-column: 2 / 3; /* 2列目から3列目まで */
    padding: 20px;
    background-color: #ffd700;
  }
  
  .right-money{
    background-color: #ffffff;
    padding: 30px;
  }
  
  .paypay{
    border: 3px solid;
    border-color: #c0c0c0;
  }

  .cash-register{
    padding: 20px;
    width: 100%;
    background-color: #ffa500;
    border-radius: 35px;
  }

.cash-register-margin{
  margin-top: 5%;
  margin-bottom: 25%;

}
  
  .right-column{
    padding: 40px;
    background-color: #ffd700;
  }
  
  .cash-register:hover{
    background-color: #ff8c00;
  }
  
  .best-goods{
    border: 2px solid;
    border-color: #a9a9a9;
  }
  .grid-item {gap: 50px;
    align-items: center;
    width: 70%;
    display: flex;
    border: 1px solid #ccc;
    padding: 0;
    text-align: left;
  }
  
  .grid-item p, h3 {
    margin: 0;
  }
  
  .product-image {
    max-width: 20%;
    height: auto;
  }
  
  .product-price{
    color: #B12704;
    font-size: 20px;
  }
```
