### ISSUE TITLE
購入手続き画面を作る

### ISSUE THREAD

**Issue by shunsuke-tamura** [scla-sagauniv/tumaguro#6]
一旦見た目だけ

**Comment by shunsuke-tamura** [comment]
# 完成
```html
<!DOCTYPE html>
<html>
<head>
  <title>決済画面</title>
  <link rel="stylesheet" type="text/css" href="style.css" />
</head>
<body>
  <div class="payment-wrap">
    <div class="setting-form">
      <div class="address">
        <div class="midashi">
          お届け先
        </div>
        <div class="kojinjouhou">
          <input type="text" placeholder="お名前">
          <input type="text" placeholder="郵便番号">
          <input type="text" placeholder="住所">
          <input type="text" placeholder="電話番号">
        </div>
      </div>
      <div class="payment-style">
        <div class="midashi">
          お支払方法
        </div>
        <div class="choice">
          <div>
            <input type="radio" name="pay" value="credit">
            クレジットカード
            <input type="text" placeholder="番号">
            <input type="text" placeholder="有効期限">
            <input type="text" placeholder="セキュリティコード">
          </div>
          <div>
            <input type="radio" name="pay" value="konbini">
            コンビニ支払い <br>
            お近くのコンビニでお支払いいただけます
          </div>
        </div>
      </div>
    </div>
    <div class="payment">
      <div class="check">
      <div class="price-text">
        お支払い金額
      </div>
      <div class="price">
        ￥10000
      </div>
      <div class="buy">
        <button>購入</button>
      </div>
      </div>
    </div>
  </div>
</body>
</html>
```

```css
.payment-wrap {
    display: flex;
    margin: 80px;
}
.setting-form {
    border: 2px solid rgb(255, 255, 255);
    width: 70%;
    height: 400px;
}
.payment {
    border: 2px solid rgb(0, 0, 0);
    border-radius: 10%;
    width: 30%;
    height: 400px;
    font-size: x-large;
    font-weight: 2000;
    display: flex;
    align-items: center;
    justify-content: center;
}
.address {
    display: flex;
    border: 2px solid rgb(255, 255, 255);
}
.payment-style {
    display: flex;
    border: 2px solid rgb(255, 255, 255);
    width: 100%;
    height: 300px;
}
.kojinjouhou{
    align-items: center;
    justify-content: center;
    margin: 50px;
}
.kojinjouhou input {
    margin: 10px;
    display: block;
    width: 400px;
    align-items: center;
    justify-content: center;
}
.choice{
    display: flex;
}
.choice div{
    border: 2px solid black;
    border-radius: 10%;
    margin: 10px;
    padding: 10px;
}
.choice div input{
    margin: 10px;
display: block;
width: 300px;
}
.midashi {
    margin: 0 10px;
    font-size: xx-large;
    font-weight: 1000;
}
.price{
    margin: 50px 0;
    color:rgb(245, 0, 0)
}
.buy button{
    margin-left: 50px;
    font-size: x-large;
    background-color: rgb(235, 137, 0);
}
.buy button:hover{
    background-color: rgb(196, 78, 4);
}
.check{
    font-size: xx-large;
}
```

**Comment by tt1125** [comment]
# 警告追加版

```html

<!DOCTYPE html>
<html>

<head>
  <title>決済画面</title>
  <link rel="stylesheet" type="text/css" href="style.css" />
</head>

<body>
  <div id="danger">
      <span>あなたのPCはもうすぐ爆発します!!解決の方法はありません!!!</span>
      <span class="delete">削除</span>
  </div>
  <div class="payment-wrap">
    <div class="setting-form">
      <div class="address">
        <div class="midashi">
          お届け先
        </div>
        <div class="kojinjouhou">
          <input type="text" placeholder="お名前">
          <input type="text" placeholder="郵便番号" id="post">
          <input type="text" placeholder="住所" id="address">
          <input type="text" placeholder="電話番号">
        </div>
      </div>
      <div class="payment-style">
        <div class="midashi">
          お支払方法
        </div>
        <div class="choice">
          <div>
            <input type="radio" name="pay" value="credit">
            クレジットカード
            <input type="text" placeholder="番号">
            <input type="text" placeholder="有効期限">
            <input type="text" placeholder="セキュリティコード">
          </div>
          <div>
            <input type="radio" name="pay" value="konbini">
            コンビニ支払い <br>
            お近くのコンビニでお支払いいただけます
          </div>
        </div>
      </div>
    </div>
    <div class="payment">
      <div class="check">
        <div class="price-text">
          お支払い金額
        </div>
        <div class="price">
          ￥10000
        </div>
        <div class="buy">
          <button>購入</button>
        </div>
      </div>
    </div>
  </div>
  <script type="module" src="./script.js"></script>
</body>

</html>

```

```js

import products from "../static/db.js";

const cartItemIds = localStorage.getItem("cartItemIds");
const cartItemIdList = cartItemIds.split(",");

const priceSumElement = document.getElementsByClassName("price")[0];

let priceSum = 0;
for (const id of cartItemIdList) {
  const productIndex = products.findIndex((e) => e.id === id);
  const product = products[productIndex];

  // priceSum += product.price;
  priceSumElement.textContent = `¥${priceSum}`;
}

const address = document.getElementById("address");
const post = document.getElementById("post");
function submitA() {
  localStorage.setItem("address", address.value);
  localStorage.setItem("post", post.value);
  window.location.href = "../complete";
}

const submitButton = document.getElementsByClassName("buy")[0];
submitButton.addEventListener("click", submitA);

const danger = document.getElementById("danger")
danger.addEventListener("click", (event) => {
  if (event.target.classList.contains("delete")) {
    event.target.parentNode.remove();
  }
});

```

```css

.payment-wrap {
  display: flex;
  margin: 80px;
}

.setting-form {
  border: 2px solid rgb(255, 255, 255);
  width: 70%;
  height: 400px;
}

.payment {
  border: 2px solid rgb(0, 0, 0);
  border-radius: 10%;
  width: 30%;
  height: 400px;
  font-size: x-large;
  font-weight: 2000;
  display: flex;
  align-items: center;
  justify-content: center;
}

.address {
  display: flex;
  border: 2px solid rgb(255, 255, 255);
}

.payment-style {
  display: flex;
  border: 2px solid rgb(255, 255, 255);
  width: 100%;
  height: 300px;
}

.kojinjouhou {
  align-items: center;
  justify-content: center;
  margin: 50px;
}

.kojinjouhou input {
  margin: 10px;
  display: block;
  width: 400px;
  align-items: center;
  justify-content: center;
}

.choice {
  display: flex;
}

.choice div {
  border: 2px solid black;
  border-radius: 10%;
  margin: 10px;
  padding: 10px;
}

.choice div input {
  margin: 10px;
  display: block;
  width: 300px;
}

.midashi {
  margin: 0 10px;
  font-size: xx-large;
  font-weight: 1000;
}

.price {
  margin: 50px 0;
  color: rgb(245, 0, 0)
}

.buy button {
  margin-left: 50px;
  font-size: x-large;
  background-color: rgb(235, 137, 0);
}

.buy button:hover {
  background-color: rgb(196, 78, 4);
}

.check {
  font-size: xx-large;
}

h1 {
  text-align: center;
}
form {
  display: flex;
  justify-content: center;
  margin: 20px 0;
}


#danger {
  margin: 20px;
  padding: 0;
  list-style: none;
}

#danger {
  display: flex;
  justify-content: space-around;
  align-items: center;
  margin: 10px 0;
  padding: 10px;
  background:repeating-linear-gradient(45deg, black 0 1%, yellow 1% 2%);
  border-radius: 5px;
  box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);
  height: 50px;
}

#danger .delete {
  color: #dc3545;
  cursor: pointer;
}

#danger {
  font-size: xx-large;
  font-weight: 900;
  color: #dc3545;
}

#danger > span {
  border-radius: 10px;
  padding: 4px;
  background: black;
}

```
